// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkME5m-eAVXjD7TQkuiHLesGcp_cd9oWw',
    appId: '1:273610746961:web:f50df96e8494053ae25c70',
    messagingSenderId: '273610746961',
    projectId: 'besports-cbb59',
    authDomain: 'besports-cbb59.firebaseapp.com',
    databaseURL: 'https://besports-cbb59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'besports-cbb59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaSwYrCDzlOyNzcObr14WGQ_TjSlAxzM8',
    appId: '1:273610746961:android:57e4a47ba2364819e25c70',
    messagingSenderId: '273610746961',
    projectId: 'besports-cbb59',
    databaseURL: 'https://besports-cbb59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'besports-cbb59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAna_kwyrsEHy-LRgk9_eKV5_5l_4yUWEE',
    appId: '1:273610746961:ios:d031b36b364cf6f6e25c70',
    messagingSenderId: '273610746961',
    projectId: 'besports-cbb59',
    databaseURL: 'https://besports-cbb59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'besports-cbb59.appspot.com',
    iosClientId: '273610746961-hq9sn3s5rki3frm42o9iskggsml9mlfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.nodevice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAna_kwyrsEHy-LRgk9_eKV5_5l_4yUWEE',
    appId: '1:273610746961:ios:c9c81a81840dbee4e25c70',
    messagingSenderId: '273610746961',
    projectId: 'besports-cbb59',
    databaseURL: 'https://besports-cbb59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'besports-cbb59.appspot.com',
    iosClientId: '273610746961-n9to58mnbj1el4cii6ncvl1glom5gn6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.nodevice.RunnerTests',
  );
}
